/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_solarexsoft_usesodemo_MainActivity */

#ifndef _Included_com_solarexsoft_usesodemo_MainActivity
#define _Included_com_solarexsoft_usesodemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_solarexsoft_usesodemo_MainActivity
 * Method:    callHelloFromSo
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_solarexsoft_usesodemo_MainActivity_callHelloFromSo
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
