/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_solarexsoft_ndkdemo_HelloNDK */

#ifndef _Included_com_solarexsoft_ndkdemo_HelloNDK
#define _Included_com_solarexsoft_ndkdemo_HelloNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_solarexsoft_ndkdemo_HelloNDK
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_solarexsoft_ndkdemo_HelloNDK_hello
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
